import { StyleSheet } from 'react-native';
import { colors } from '../theme';

export const styles = StyleSheet.create({
  headerActions: { flexDirection: 'row', gap: 6 },
  photoPanel: { flexShrink: 0, marginBottom: 4 },
  highlightOutline: { borderWidth: 3, borderColor: colors.orange, backgroundColor: 'rgba(139,50,40,0.16)', zIndex: 2 },
  screen: { flex: 1, backgroundColor: colors.paper },
  homeScroll: { flex: 1 },
  homeContent: { flexGrow: 1, paddingHorizontal: 24, paddingTop: 16, paddingBottom: 24, maxWidth: 720, width: '100%', alignSelf: 'center' },
  captureHeader: { minHeight: 48, flexShrink: 0, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingVertical: 2 },
  captureTitle: { color: colors.ink, fontSize: 20, fontWeight: '700' },
  photoStatus: { position: 'absolute', top: 16, alignSelf: 'center', backgroundColor: colors.white, padding: 12, flexDirection: 'row', alignItems: 'center', gap: 8, borderRadius: 8 },
  reviewContent: { flex: 1, paddingHorizontal: 16, maxWidth: 720, width: '100%', alignSelf: 'center' },
  header: { flexDirection: 'row', alignItems: 'center', gap: 16, marginBottom: 16 },
  brandMark: { width: 40, height: 48, borderRadius: 8, backgroundColor: colors.ink, alignItems: 'center', justifyContent: 'center' },
  brandKanji: { color: colors.white, fontSize: 28, fontWeight: '800' },
  brandCopy: { flex: 1 },
  eyebrow: { color: colors.muted, fontSize: 12, fontWeight: '700', letterSpacing: 1.7, marginBottom: 3 },
  heading: { color: colors.ink, fontSize: 24, lineHeight: 30, fontWeight: '800', letterSpacing: -0.5 },
  newCaptureButton: { minHeight: 44, justifyContent: 'center', borderRadius: 8, borderWidth: 1, borderColor: colors.line, paddingHorizontal: 14, paddingVertical: 8 },
  newCaptureText: { color: colors.ink, fontSize: 14, fontWeight: '700' },
  sectionLabel: { color: colors.muted, fontSize: 12, fontWeight: '700', letterSpacing: 1.3 },
  reviewBody: { flex: 1, minHeight: 0 },
  textContent: { paddingTop: 8, paddingBottom: 24, gap: 8 },
  helperText: { color: colors.muted, fontSize: 14, lineHeight: 18, marginTop: 4 },
  imageViewport: { flex: 1, minHeight: 0, width: '100%', overflow: 'hidden', borderRadius: 12, backgroundColor: colors.greenWash, marginTop: 0 },
  image: { position: 'absolute', top: 0, right: 0, bottom: 0, left: 0 },
  regionOutline: { position: 'absolute', borderWidth: 1.5, borderColor: colors.orange, backgroundColor: 'rgba(255,255,255,0.12)', borderRadius: 3 },
  previewStatus: { flexDirection: 'row', alignItems: 'center', gap: 8, marginTop: 12 },
  previewStatusText: { color: colors.muted, fontSize: 14, lineHeight: 18, marginTop: 8 },
  findingCard: { backgroundColor: colors.white, borderColor: colors.line, borderWidth: 1, borderRadius: 8, padding: 16 },
  selectedFinding: { borderColor: colors.ink, borderWidth: 2, backgroundColor: colors.white },
  findingTextButton: { flex: 1, minHeight: 44, justifyContent: 'center' },
  findingRaw: { flex: 1, color: colors.ink, fontSize: 15, lineHeight: 21 },
  confidence: { color: colors.muted, fontSize: 12, marginLeft: 4 },
  inlineEditor: { minHeight: 64, color: colors.ink, fontSize: 18, lineHeight: 28, backgroundColor: colors.white, borderColor: colors.line, borderWidth: 1, borderRadius: 8, padding: 8, marginTop: 8 },
  manualEntry: { backgroundColor: colors.card, borderColor: colors.line, borderWidth: 1, borderRadius: 12, padding: 12 },
  failureCard: { padding: 16, borderRadius: 12, backgroundColor: colors.greenWash, marginBottom: 12 },
  failureTitle: { color: colors.ink, fontSize: 15, fontWeight: '700' },
  disclosureButton: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', minHeight: 44, marginTop: 8, borderTopWidth: 1, borderTopColor: colors.line },
  disclosureText: { color: colors.ink, fontSize: 16, fontWeight: '700' },
  disclosureChevron: { color: colors.green, fontSize: 18, fontWeight: '600' },
  rawCard: { backgroundColor: colors.greenWash, borderRadius: 12, padding: 12, marginTop: 2 },
  rawText: { color: colors.ink, fontSize: 14, lineHeight: 22, marginTop: 8 },
  retryButton: { minHeight: 44, alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: colors.line, borderRadius: 12, marginTop: 10 },
  retryButtonText: { color: colors.green, fontSize: 13, fontWeight: '700' },
  emptyState: { minHeight: 280, justifyContent: 'center', alignItems: 'flex-start', backgroundColor: colors.card, borderRadius: 12, borderWidth: 2, borderColor: colors.ink, padding: 24, marginVertical: 24 },
  emptyIndex: { color: colors.muted, fontSize: 12, fontWeight: '700', letterSpacing: 1.2, marginBottom: 13 },
  emptyTitle: { color: colors.ink, fontSize: 32, lineHeight: 38, fontWeight: '800', marginTop: 16 },
  emptyCopy: { color: colors.muted, fontSize: 16, lineHeight: 24, marginTop: 8 },
  sourceRow: { flexDirection: 'row', gap: 10, marginTop: 18 },
  primaryButton: { flex: 1, minHeight: 88, backgroundColor: colors.ink, borderRadius: 8, padding: 16, justifyContent: 'space-between' },
  secondaryButton: { flex: 1, minHeight: 88, backgroundColor: colors.white, borderColor: colors.ink, borderWidth: 2, borderRadius: 8, padding: 16, justifyContent: 'space-between' },
  buttonKicker: { color: '#DADADA', fontSize: 12, letterSpacing: 1.3, fontWeight: '700' },
  primaryButtonText: { color: colors.white, fontSize: 16, fontWeight: '700' },
  secondaryButtonText: { color: colors.ink, fontSize: 16, fontWeight: '700' },
  homeSpinner: { marginTop: 14 },
  privacyNote: { color: colors.muted, fontSize: 14, textAlign: 'center', marginTop: 16 },
  errorMessage: { color: '#A34735', fontSize: 14, lineHeight: 18, marginTop: 5, paddingHorizontal: 3 },
  noticeMessage: { color: colors.green, fontSize: 14, lineHeight: 18, marginTop: 4, paddingHorizontal: 2 },
  pressed: { opacity: 0.82 },
  disabled: { opacity: 0.55 },
});
