import { StyleSheet } from 'react-native';
import { colors } from '../theme';

export const styles = StyleSheet.create({
  headerActions: { flexDirection: 'row', gap: 6 },
  photoPanel: { flexShrink: 0, marginBottom: 4 },
  highlightOutline: { borderWidth: 3, borderColor: colors.orange, backgroundColor: 'rgba(139,50,40,0.16)', zIndex: 2 },
  rubyBreak: { width: '100%', height: 0 },
  wordRuby: { alignItems: 'center', alignSelf: 'flex-start', maxWidth: '100%' },
  wordSurface: { fontSize: 24, lineHeight: 32, fontWeight: '700', color: colors.ink },
  characterToggle: { minHeight: 44, justifyContent: 'center', marginTop: 4 },
  characterToggleText: { fontSize: 14, fontWeight: '700', color: colors.ink },
  characterEntry: { padding: 12, backgroundColor: colors.greenWash, borderRadius: 8, marginTop: 8 },
  characterTitle: { fontSize: 24, lineHeight: 32, fontWeight: '700', color: colors.ink },
  characterReading: { fontSize: 14, lineHeight: 21, color: colors.muted, marginTop: 4 },
  screen: { flex: 1, backgroundColor: colors.paper },
  homeScroll: { flex: 1 },
  homeContent: { flexGrow: 1, paddingHorizontal: 24, paddingTop: 16, paddingBottom: 24, maxWidth: 720, width: '100%', alignSelf: 'center' },
  captureHeader: { minHeight: 48, flexShrink: 0, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingVertical: 2 },
  captureTitle: { color: colors.ink, fontSize: 20, fontWeight: '700' },
  brushHint: { color: colors.muted, fontSize: 12, lineHeight: 18, marginTop: 4 },
  photoStatus: { position: 'absolute', top: 16, alignSelf: 'center', backgroundColor: colors.white, padding: 12, flexDirection: 'row', alignItems: 'center', gap: 8, borderRadius: 8 },
  reviewContent: { flex: 1, paddingHorizontal: 16, maxWidth: 720, width: '100%', alignSelf: 'center' },
  header: { flexDirection: 'row', alignItems: 'center', gap: 16, marginBottom: 16 },
  brandMark: { width: 40, height: 48, borderRadius: 8, backgroundColor: colors.ink, alignItems: 'center', justifyContent: 'center' },
  brandKanji: { color: colors.white, fontSize: 28, fontWeight: '800' },
  brandCopy: { flex: 1 },
  eyebrow: { color: colors.muted, fontSize: 12, fontWeight: '700', letterSpacing: 1.7, marginBottom: 3 },
  heading: { color: colors.ink, fontSize: 24, lineHeight: 30, fontWeight: '800', letterSpacing: -0.5 },
  newCaptureButton: { minHeight: 44, justifyContent: 'center', borderRadius: 8, borderWidth: 1, borderColor: colors.line, paddingHorizontal: 14, paddingVertical: 8 },
  newCaptureText: { color: colors.ink, fontSize: 14, fontWeight: '700' },
  sectionLabel: { color: colors.muted, fontSize: 12, fontWeight: '700', letterSpacing: 1.3 },
  reviewBody: { flex: 1, minHeight: 0 },
  textContent: { paddingTop: 8, paddingBottom: 24, gap: 8 },
  helperText: { color: colors.muted, fontSize: 14, lineHeight: 18, marginTop: 4 },
  imageViewport: { flex: 1, minHeight: 0, width: '100%', overflow: 'hidden', borderRadius: 12, backgroundColor: colors.greenWash, marginTop: 0 },
  image: { position: 'absolute', top: 0, right: 0, bottom: 0, left: 0 },
  regionOutline: { position: 'absolute', borderWidth: 1.5, borderColor: colors.orange, backgroundColor: 'rgba(255,255,255,0.12)', borderRadius: 3 },
  removedRegionOutline: { borderColor: colors.orange, backgroundColor: 'rgba(255,255,255,0.86)' },
  brushToolbar: { flexShrink: 0, flexDirection: 'row', gap: 8, marginTop: 8 },
  brushButton: { flex: 1, minHeight: 48, borderRadius: 8, borderWidth: 2, borderColor: colors.ink, justifyContent: 'center', alignItems: 'center', backgroundColor: colors.white },
  brushButtonActive: { backgroundColor: colors.ink },
  brushButtonText: { color: colors.ink, fontSize: 16, fontWeight: '700' },
  brushButtonTextActive: { color: colors.white },
  undoButton: { minHeight: 48, paddingHorizontal: 16, justifyContent: 'center', borderRadius: 8, backgroundColor: colors.greenWash },
  brushCursor: { position: 'absolute', zIndex: 4, width: 44, height: 44, borderRadius: 22, borderWidth: 3, borderColor: colors.ink, backgroundColor: 'rgba(255,255,255,0.5)' },
  furiganaNote: { color: colors.muted, fontSize: 12, lineHeight: 18, marginTop: 4 },
  translationError: { color: colors.orange, fontSize: 12, lineHeight: 18, marginTop: 6 },
  previewStatus: { flexDirection: 'row', alignItems: 'center', gap: 8, marginTop: 12 },
  previewStatusText: { color: colors.muted, fontSize: 14, lineHeight: 18, marginTop: 8 },
  previewFurigana: { flexDirection: 'row', flexWrap: 'wrap', alignItems: 'flex-end', rowGap: 8, marginTop: 10 },
  previewFuriganaToken: { alignItems: 'center', justifyContent: 'flex-end', marginRight: 1 },
  previewReading: { minHeight: 20, color: colors.ink, fontSize: 14, lineHeight: 20, textAlign: 'center' },
  previewFuriganaSurface: { color: colors.ink, fontSize: 24, lineHeight: 32, fontWeight: '700' },
  previewFuriganaGap: { color: colors.ink, fontSize: 24, lineHeight: 32 },
  previewMeanings: { borderTopColor: colors.line, borderTopWidth: 1, marginTop: 12, paddingTop: 10 },
  previewMeaningHeading: { color: colors.muted, fontSize: 12, fontWeight: '700', letterSpacing: 1 },
  previewMeaningRow: { borderBottomColor: colors.line, borderBottomWidth: StyleSheet.hairlineWidth, paddingVertical: 8 },
  previewWordLine: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  dictionaryLabel: { color: colors.muted, fontSize: 12, fontWeight: '700', letterSpacing: 0.8, marginTop: 7 },
  previewMeaning: { color: colors.ink, fontSize: 16, lineHeight: 24, marginTop: 4 },
  previewUnknown: { color: colors.muted, fontSize: 14, fontStyle: 'italic', marginTop: 3 },
  previewExtraSense: { color: colors.muted, fontSize: 16, lineHeight: 24, paddingLeft: 8, marginTop: 4 },
  previewCandidate: { minHeight: 44, flexDirection: 'row', alignItems: 'center', gap: 8, paddingVertical: 5 },
  previewCandidateText: { flex: 1, flexShrink: 1, minWidth: 0 },
  previewCandidateMark: { color: colors.green, fontSize: 12, width: 14 },
  previewCandidateHint: { color: colors.muted, fontSize: 12, fontWeight: '700', letterSpacing: 0.6 },
  previewDisclaimer: { color: colors.muted, fontSize: 12, lineHeight: 18, marginTop: 8 },
  previewError: { borderRadius: 10, backgroundColor: colors.greenWash, padding: 10, marginTop: 9 },
  previewErrorText: { color: colors.muted, fontSize: 14, lineHeight: 18 },
  previewRetryButton: { minHeight: 44, alignSelf: 'flex-start', justifyContent: 'center', paddingHorizontal: 12, borderRadius: 9, backgroundColor: colors.greenWash, marginTop: 8 },
  previewRetryPressed: { opacity: 0.72 },
  previewRetryText: { color: colors.green, fontSize: 12, fontWeight: '700' },
  findingCard: { backgroundColor: colors.white, borderColor: colors.line, borderWidth: 1, borderRadius: 8, padding: 16 },
  selectedFinding: { borderColor: colors.ink, borderWidth: 2, backgroundColor: colors.white },
  excludedFinding: { backgroundColor: colors.greenWash, opacity: 0.86 },
  findingHeader: { flexDirection: 'row', alignItems: 'center', gap: 8, minHeight: 44 },
  findingSelect: { width: 44, minHeight: 44, flexShrink: 0, alignItems: 'center', justifyContent: 'center' },
  checkbox: { width: 22, height: 22, borderRadius: 7, borderWidth: 1, borderColor: colors.ink, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.white },
  checkboxSelected: { borderColor: colors.green, backgroundColor: colors.green },
  checkboxMark: { color: colors.white, fontSize: 13, fontWeight: '700' },
  findingTextButton: { flex: 1, minHeight: 44, justifyContent: 'center' },
  findingRaw: { flex: 1, color: colors.ink, fontSize: 15, lineHeight: 21 },
  confidence: { color: colors.muted, fontSize: 12, marginLeft: 4 },
  smallAction: { minHeight: 44, paddingHorizontal: 8, justifyContent: 'center' },
  restoreText: { color: colors.green, fontSize: 14, fontWeight: '700' },
  inlineEditor: { minHeight: 64, color: colors.ink, fontSize: 18, lineHeight: 28, backgroundColor: colors.white, borderColor: colors.line, borderWidth: 1, borderRadius: 8, padding: 8, marginTop: 8 },
  manualEntry: { backgroundColor: colors.card, borderColor: colors.line, borderWidth: 1, borderRadius: 12, padding: 12 },
  failureCard: { padding: 16, borderRadius: 12, backgroundColor: colors.greenWash, marginBottom: 12 },
  failureTitle: { color: colors.ink, fontSize: 15, fontWeight: '700' },
  disclosureButton: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', minHeight: 44, marginTop: 8, borderTopWidth: 1, borderTopColor: colors.line },
  disclosureText: { color: colors.ink, fontSize: 16, fontWeight: '700' },
  disclosureChevron: { color: colors.green, fontSize: 18, fontWeight: '600' },
  rawCard: { backgroundColor: colors.greenWash, borderRadius: 12, padding: 12, marginTop: 2 },
  rawText: { color: colors.ink, fontSize: 14, lineHeight: 22, marginTop: 8 },
  selectionPreview: { color: colors.ink, fontSize: 14, lineHeight: 18, marginTop: 3 },
  retryButton: { minHeight: 44, alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: colors.line, borderRadius: 12, marginTop: 10 },
  retryButtonText: { color: colors.green, fontSize: 13, fontWeight: '700' },
  emptyState: { minHeight: 280, justifyContent: 'center', alignItems: 'flex-start', backgroundColor: colors.card, borderRadius: 12, borderWidth: 2, borderColor: colors.ink, padding: 24, marginVertical: 24 },
  emptyIndex: { color: colors.muted, fontSize: 12, fontWeight: '700', letterSpacing: 1.2, marginBottom: 13 },
  emptyTitle: { color: colors.ink, fontSize: 32, lineHeight: 38, fontWeight: '800', marginTop: 16 },
  emptyCopy: { color: colors.muted, fontSize: 16, lineHeight: 24, marginTop: 8 },
  sourceRow: { flexDirection: 'row', gap: 10, marginTop: 18 },
  primaryButton: { flex: 1, minHeight: 88, backgroundColor: colors.ink, borderRadius: 8, padding: 16, justifyContent: 'space-between' },
  secondaryButton: { flex: 1, minHeight: 88, backgroundColor: colors.white, borderColor: colors.ink, borderWidth: 2, borderRadius: 8, padding: 16, justifyContent: 'space-between' },
  buttonKicker: { color: '#DADADA', fontSize: 12, letterSpacing: 1.3, fontWeight: '700' },
  primaryButtonText: { color: colors.white, fontSize: 16, fontWeight: '700' },
  secondaryButtonText: { color: colors.ink, fontSize: 16, fontWeight: '700' },
  homeSpinner: { marginTop: 14 },
  privacyNote: { color: colors.muted, fontSize: 14, textAlign: 'center', marginTop: 16 },
  errorMessage: { color: '#A34735', fontSize: 14, lineHeight: 18, marginTop: 5, paddingHorizontal: 3 },
  noticeMessage: { color: colors.green, fontSize: 14, lineHeight: 18, marginTop: 4, paddingHorizontal: 2 },
  pressed: { opacity: 0.82 },
  disabled: { opacity: 0.55 },
});
